// packages/vue/src/components/TextField.vue
<script lang="ts">
export type TextFieldSize = 's' | 'm' | 'l';
</script>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { createId } from '@iskra-ui/core';
import { useIskraT } from '../i18n/useIskraT.js';
import { cx } from '../utils/cx.js';

const props = withDefaults(
  defineProps<{
    /** Controlled value (v-model). */
    modelValue?: string;
    size?: TextFieldSize;
    label?: string;
    hint?: string;
    /** Error message (string) or boolean error state. */
    error?: string | boolean;
    required?: boolean;
    clearable?: boolean;
    disabled?: boolean;
    id?: string;
    placeholder?: string;
    type?: string;
    clearLabel?: string;
  }>(),
  {
    modelValue: '',
    size: 'm',
    required: false,
    clearable: false,
    disabled: false,
    type: 'text',
  },
);

const t = useIskraT();
const resolvedClearLabel = computed(() => props.clearLabel ?? t('common.clear'));

const emit = defineEmits<{ 'update:modelValue': [value: string]; clear: [] }>();

const inputRef = ref<HTMLInputElement>();
const inputId = computed(() => props.id ?? createId('ik-tf'));
const errText = computed(() => (typeof props.error === 'string' ? props.error : null));
const isError = computed(() => Boolean(props.error));
const showClear = computed(
  () => props.clearable && !props.disabled && (props.modelValue ?? '').length > 0,
);
const fieldCls = computed(() =>
  cx(
    'ik-tf-field',
    `ik-tf-${props.size}`,
    isError.value && 'is-error',
    props.disabled && 'is-disabled',
  ),
);
const describedBy = computed(() =>
  errText.value || props.hint ? `${inputId.value}-msg` : undefined,
);

function onInput(e: Event) {
  emit('update:modelValue', (e.target as HTMLInputElement).value);
}

function onClear() {
  emit('update:modelValue', '');
  emit('clear');
  inputRef.value?.focus();
}
</script>

<template>
  <div class="ik-tf-wrap">
    <label v-if="label" class="ik-tf-label" :for="inputId">
      {{ label }}
      <span v-if="required" class="ik-tf-req" aria-hidden="true">*</span>
    </label>
    <div :class="fieldCls">
      <span v-if="$slots.iconBefore" class="ik-tf-ico"><slot name="iconBefore" /></span>
      <input
        :id="inputId"
        ref="inputRef"
        class="ik-tf-input"
        :type="type"
        :value="modelValue"
        :disabled="disabled"
        :placeholder="placeholder"
        :aria-invalid="isError || undefined"
        :aria-describedby="describedBy"
        @input="onInput"
      />
      <button
        v-if="showClear"
        type="button"
        class="ik-tf-clear"
        :aria-label="resolvedClearLabel"
        @click="onClear"
      >
        <svg
          width="13"
          height="13"
          viewBox="0 0 16 16"
          fill="none"
          stroke="currentColor"
          stroke-width="1.6"
          stroke-linecap="round"
          aria-hidden="true"
        >
          <line x1="4" y1="4" x2="12" y2="12" />
          <line x1="12" y1="4" x2="4" y2="12" />
        </svg>
      </button>
    </div>
    <div
      v-if="errText || hint"
      :id="`${inputId}-msg`"
      :class="cx('ik-tf-msg', isError && 'is-error')"
    >
      {{ errText || hint }}
    </div>
  </div>
</template>

// packages/react/src/components/TextField/TextField.tsx
import { useId, useRef, useState, type InputHTMLAttributes, type ReactNode } from 'react';
import { useIskraT } from '../../i18n/useIskraT.js';
import { cx } from '../../utils/cx.js';
import './TextField.css';

export type TextFieldSize = 's' | 'm' | 'l';

export interface TextFieldProps extends Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'size' | 'prefix'
> {
  size?: TextFieldSize;
  label?: ReactNode;
  hint?: ReactNode;
  /** Error message (string) or boolean error state. */
  error?: ReactNode | boolean;
  required?: boolean;
  iconBefore?: ReactNode;
  clearable?: boolean;
  onClear?: () => void;
  clearLabel?: string;
  wrapClassName?: string;
}

/**
 * TextField — single-line text input with label, hint, error, leading icon and
 * an optional clear button. Controlled or uncontrolled. Wires `aria-describedby`
 * / `aria-invalid` for screen readers.
 */
export function TextField({
  size = 'm',
  label,
  hint,
  error,
  required = false,
  iconBefore,
  clearable = false,
  onClear,
  disabled = false,
  value,
  defaultValue,
  onChange,
  id,
  className,
  wrapClassName,
  clearLabel,
  ...rest
}: TextFieldProps) {
  const t = useIskraT();
  const resolvedClearLabel = clearLabel ?? t('common.clear');
  const autoId = useId();
  const inputId = id ?? `ik-tf-${autoId}`;
  const inputRef = useRef<HTMLInputElement>(null);

  const controlled = value != null;
  const [hasVal, setHasVal] = useState(
    controlled ? String(value).length > 0 : String(defaultValue ?? '').length > 0,
  );
  const showClear = clearable && !disabled && (controlled ? String(value).length > 0 : hasVal);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!controlled) setHasVal(e.target.value.length > 0);
    onChange?.(e);
  };

  const handleClear = () => {
    const el = inputRef.current;
    if (el) {
      const setter = Object.getOwnPropertyDescriptor(
        window.HTMLInputElement.prototype,
        'value',
      )?.set;
      setter?.call(el, '');
      el.dispatchEvent(new Event('input', { bubbles: true }));
      el.focus();
    }
    if (!controlled) setHasVal(false);
    onClear?.();
  };

  const errText = typeof error === 'string' ? error : null;
  const isError = Boolean(error);

  return (
    <div className={cx('ik-tf-wrap', wrapClassName)}>
      {label && (
        <label className="ik-tf-label" htmlFor={inputId}>
          {label}
          {required && (
            <span className="ik-tf-req" aria-hidden="true">
              *
            </span>
          )}
        </label>
      )}
      <div
        className={cx(
          'ik-tf-field',
          `ik-tf-${size}`,
          isError && 'is-error',
          disabled && 'is-disabled',
          className,
        )}
      >
        {iconBefore && <span className="ik-tf-ico">{iconBefore}</span>}
        <input
          ref={inputRef}
          id={inputId}
          className="ik-tf-input"
          disabled={disabled}
          value={value}
          defaultValue={defaultValue}
          onChange={handleChange}
          aria-invalid={isError || undefined}
          aria-describedby={errText || hint ? `${inputId}-msg` : undefined}
          {...rest}
        />
        {showClear && (
          <button
            type="button"
            className="ik-tf-clear"
            onClick={handleClear}
            aria-label={resolvedClearLabel}
          >
            <svg
              width="13"
              height="13"
              viewBox="0 0 16 16"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.6"
              strokeLinecap="round"
              aria-hidden="true"
            >
              <line x1="4" y1="4" x2="12" y2="12" />
              <line x1="12" y1="4" x2="4" y2="12" />
            </svg>
          </button>
        )}
      </div>
      {(errText || hint) && (
        <div id={`${inputId}-msg`} className={cx('ik-tf-msg', isError && 'is-error')}>
          {errText || hint}
        </div>
      )}
    </div>
  );
}
