// packages/vue/src/components/Popover.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { createId, getTriggerAria } from '@iskra-ui/core'
import { cx } from '../utils/cx.js'

export type PopoverPlacement =
  | 'bottom-start'
  | 'bottom-end'
  | 'bottom'
  | 'top-start'
  | 'top-end'
  | 'top'

const props = withDefaults(
  defineProps<{
    open?: boolean
    placement?: PopoverPlacement
    offset?: number
    closeOnEsc?: boolean
    closeOnClickOutside?: boolean
    panelClassName?: string
    id?: string
  }>(),
  {
    placement: 'bottom-end',
    offset: 8,
    closeOnEsc: true,
    closeOnClickOutside: true,
  },
)

const emit = defineEmits<{ 'update:open': [value: boolean]; openChange: [value: boolean] }>()

const anchorRef = ref<HTMLElement | null>(null)
const panelRef = ref<HTMLElement | null>(null)
const panelId = computed(() => props.id ?? createId('ik-popover'))
const pos = ref<{ top: number; left: number } | null>(null)

const isOpen = computed({
  get: () => props.open ?? false,
  set: (v: boolean) => {
    emit('update:open', v)
    emit('openChange', v)
  },
})

const triggerAria = computed(() => getTriggerAria(isOpen.value, panelId.value))

function updatePosition() {
  const anchor = anchorRef.value
  const panel = panelRef.value
  if (!anchor || !panel || !isOpen.value) return
  const ar = anchor.getBoundingClientRect()
  const pr = panel.getBoundingClientRect()
  const offset = props.offset
  let top = ar.bottom + offset
  let left = ar.right - pr.width
  if (props.placement === 'bottom-start') left = ar.left
  const pad = 8
  left = Math.max(pad, Math.min(left, window.innerWidth - pr.width - pad))
  top = Math.max(pad, Math.min(top, window.innerHeight - pr.height - pad))
  pos.value = { top, left }
}

function toggle() {
  isOpen.value = !isOpen.value
}

function onKey(e: KeyboardEvent) {
  if (props.closeOnEsc && e.key === 'Escape') isOpen.value = false
}

function onDown(e: MouseEvent) {
  if (!props.closeOnClickOutside) return
  const t = e.target as Node
  if (anchorRef.value?.contains(t) || panelRef.value?.contains(t)) return
  isOpen.value = false
}

watch(isOpen, (v) => {
  if (v) requestAnimationFrame(updatePosition)
  else pos.value = null
})

onMounted(() => {
  document.addEventListener('keydown', onKey)
  document.addEventListener('mousedown', onDown)
  window.addEventListener('resize', updatePosition)
  window.addEventListener('scroll', updatePosition, true)
})

onUnmounted(() => {
  document.removeEventListener('keydown', onKey)
  document.removeEventListener('mousedown', onDown)
  window.removeEventListener('resize', updatePosition)
  window.removeEventListener('scroll', updatePosition, true)
})
</script>

<template>
  <span ref="anchorRef" class="ik-popover-anchor" @click="toggle">
    <slot
      name="trigger"
      :aria-expanded="triggerAria['aria-expanded']"
      :aria-controls="isOpen ? panelId : undefined"
    />
  </span>
  <Teleport to="body">
    <div
      v-if="isOpen"
      :id="panelId"
      ref="panelRef"
      role="dialog"
      :class="cx('ik-popover-panel', panelClassName)"
      :style="
        pos
          ? { top: `${pos.top}px`, left: `${pos.left}px`, visibility: 'visible' }
          : { top: '-9999px', left: '-9999px', visibility: 'hidden' }
      "
      @mousedown.stop
    >
      <slot />
    </div>
  </Teleport>
</template>

// packages/react/src/components/Popover/Popover.tsx
import {
  cloneElement,
  isValidElement,
  useCallback,
  useEffect,
  useId,
  useRef,
  useState,
  type MouseEvent as ReactMouseEvent,
  type ReactElement,
  type ReactNode,
} from 'react'
import { createPortal } from 'react-dom'
import { getTriggerAria } from '@iskra-ui/core'
import { cx } from '../../utils/cx.js'
import { useAnchorPosition, type PopoverPlacement } from '../../utils/useAnchorPosition.js'
import './Popover.css'

export type { PopoverPlacement }

export interface PopoverProps {
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  trigger: ReactElement
  children: ReactNode
  placement?: PopoverPlacement
  offset?: number
  closeOnEsc?: boolean
  closeOnClickOutside?: boolean
  panelClassName?: string
  id?: string
}

/** Popover — anchored floating panel for notifications, menus, filters. */
export function Popover({
  open: openProp,
  defaultOpen = false,
  onOpenChange,
  trigger,
  children,
  placement = 'bottom-end',
  offset = 8,
  closeOnEsc = true,
  closeOnClickOutside = true,
  panelClassName,
  id: idProp,
}: PopoverProps) {
  const autoId = useId()
  const panelId = idProp ?? `ik-popover-${autoId}`
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen)
  const controlled = openProp !== undefined
  const open = controlled ? openProp : uncontrolledOpen

  const anchorRef = useRef<HTMLSpanElement>(null)
  const panelRef = useRef<HTMLDivElement>(null)

  const setOpen = useCallback(
    (next: boolean) => {
      if (!controlled) setUncontrolledOpen(next)
      onOpenChange?.(next)
    },
    [controlled, onOpenChange],
  )

  const pos = useAnchorPosition(open, anchorRef, panelRef, placement, offset)

  useEffect(() => {
    if (!open || !closeOnEsc) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false)
    }
    document.addEventListener('keydown', onKey)
    return () => document.removeEventListener('keydown', onKey)
  }, [open, closeOnEsc, setOpen])

  useEffect(() => {
    if (!open || !closeOnClickOutside) return
    const onDown = (e: MouseEvent) => {
      const t = e.target as Node
      if (anchorRef.current?.contains(t) || panelRef.current?.contains(t)) return
      setOpen(false)
    }
    document.addEventListener('mousedown', onDown)
    return () => document.removeEventListener('mousedown', onDown)
  }, [open, closeOnClickOutside, setOpen])

  const triggerAria = getTriggerAria(open, panelId)

  const handleTriggerClick = (e: ReactMouseEvent) => {
    if (isValidElement(trigger)) {
      const props = trigger.props as { onClick?: (ev: ReactMouseEvent) => void }
      props.onClick?.(e)
    }
    setOpen(!open)
  }

  const mergedTrigger = isValidElement(trigger)
    ? cloneElement(trigger, {
        onClick: handleTriggerClick,
        'aria-expanded': triggerAria['aria-expanded'],
        'aria-controls': open ? panelId : undefined,
      } as Record<string, unknown>)
    : trigger

  return (
    <>
      <span ref={anchorRef} className="ik-popover-anchor" style={{ display: 'inline-flex' }}>
        {mergedTrigger}
      </span>
      {open &&
        typeof document !== 'undefined' &&
        createPortal(
          <div
            ref={panelRef}
            id={panelId}
            role="dialog"
            className={cx('ik-popover-panel', panelClassName)}
            style={
              pos
                ? { top: pos.top, left: pos.left, visibility: 'visible' as const }
                : { top: -9999, left: -9999, visibility: 'hidden' as const }
            }
            onMouseDown={(e) => e.stopPropagation()}
          >
            {children}
          </div>,
          document.body,
        )}
    </>
  )
}
