// packages/vue/src/components/Sheet.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch, computed } from 'vue';
import { createFocusTrap } from '@iskra-ui/core';
import { useIskraT } from '../i18n/useIskraT.js';
import { cx } from '../utils/cx.js';

export type SheetSnap = 'content' | 'half' | 'full';

const props = withDefaults(
  defineProps<{
    open: boolean;
    title?: string;
    description?: string;
    snap?: SheetSnap;
    showHandle?: boolean;
    dismissible?: boolean;
    showClose?: boolean;
    closeLabel?: string;
  }>(),
  {
    snap: 'content',
    showHandle: true,
    dismissible: true,
    showClose: true,
  },
);

const t = useIskraT();
const resolvedCloseLabel = computed(() => props.closeLabel ?? t('common.close'));

const emit = defineEmits<{ 'update:open': [open: boolean] }>();

const sheetRef = ref<HTMLDivElement | null>(null);
const prevFocus = ref<HTMLElement | null>(null);
let trap: ReturnType<typeof createFocusTrap> | null = null;

const handleClose = () => emit('update:open', false);

watch(
  () => props.open,
  (open) => {
    if (open) {
      prevFocus.value = document.activeElement as HTMLElement | null;
      document.body.style.overflow = 'hidden';
      requestAnimationFrame(() => {
        if (sheetRef.value) trap = createFocusTrap(sheetRef.value);
        trap?.activate();
      });
      return;
    }
    trap?.deactivate();
    trap = null;
    document.body.style.overflow = '';
    prevFocus.value?.focus();
  },
);

function onKey(e: KeyboardEvent) {
  if (props.dismissible && props.open && e.key === 'Escape') handleClose();
}

function onOverlayMouseDown(e: MouseEvent) {
  if (props.dismissible && e.target === e.currentTarget) handleClose();
}

onMounted(() => document.addEventListener('keydown', onKey));
onUnmounted(() => {
  document.removeEventListener('keydown', onKey);
  trap?.deactivate();
  document.body.style.overflow = '';
});
</script>

<template>
  <Teleport to="body">
    <div v-if="open" class="ik-sheet-overlay" @mousedown="onOverlayMouseDown">
      <div
        ref="sheetRef"
        :class="cx('ik-sheet', `ik-sheet-snap-${snap}`)"
        role="dialog"
        aria-modal="true"
        :aria-labelledby="title ? 'ik-sheet-title' : undefined"
        :aria-describedby="description ? 'ik-sheet-desc' : undefined"
        tabindex="-1"
      >
        <div v-if="showHandle" class="ik-sheet-handle" aria-hidden="true">
          <span class="ik-sheet-handle-bar" />
        </div>
        <div v-if="title || showClose" class="ik-sheet-header">
          <div>
            <div v-if="title" id="ik-sheet-title" class="ik-sheet-title">{{ title }}</div>
            <div v-if="description" id="ik-sheet-desc" class="ik-sheet-desc">{{ description }}</div>
          </div>
          <button
            v-if="showClose"
            type="button"
            class="ik-sheet-close"
            :aria-label="resolvedCloseLabel"
            @click="handleClose"
          >
            <svg
              width="13"
              height="13"
              viewBox="0 0 16 16"
              fill="none"
              stroke="currentColor"
              stroke-width="1.6"
              aria-hidden="true"
            >
              <line x1="4" y1="4" x2="12" y2="12" />
              <line x1="12" y1="4" x2="4" y2="12" />
            </svg>
          </button>
        </div>
        <div v-if="$slots.default" class="ik-sheet-body">
          <slot />
        </div>
        <div v-if="$slots.footer" class="ik-sheet-footer">
          <slot name="footer" />
        </div>
      </div>
    </div>
  </Teleport>
</template>

// packages/react/src/components/Sheet/Sheet.tsx
import { useEffect, useRef, type MouseEvent, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { useIskraT } from '../../i18n/useIskraT.js';
import { useFocusTrap } from '../../utils/useFocusTrap.js';
import { cx } from '../../utils/cx.js';
import './Sheet.css';

export type SheetSnap = 'content' | 'half' | 'full';

export interface SheetProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  title?: ReactNode;
  description?: ReactNode;
  children?: ReactNode;
  footer?: ReactNode;
  snap?: SheetSnap;
  showHandle?: boolean;
  dismissible?: boolean;
  showClose?: boolean;
  closeLabel?: string;
  className?: string;
  returnFocusRef?: React.RefObject<HTMLElement | null>;
}

/**
 * Sheet — bottom panel for compact forms and actions. Use instead of `Modal` on
 * narrow viewports when a full-screen takeover is too heavy.
 */
export function Sheet({
  open,
  onOpenChange,
  title,
  description,
  children,
  footer,
  snap = 'content',
  showHandle = true,
  dismissible = true,
  showClose = true,
  closeLabel,
  className,
  returnFocusRef,
}: SheetProps) {
  const t = useIskraT();
  const resolvedCloseLabel = closeLabel ?? t('common.close');
  const sheetRef = useRef<HTMLDivElement>(null);
  const prevFocusRef = useRef<HTMLElement | null>(null);
  useFocusTrap(sheetRef, open);

  const handleClose = () => onOpenChange(false);

  useEffect(() => {
    if (open) {
      prevFocusRef.current = document.activeElement as HTMLElement | null;
      return;
    }
    const target = returnFocusRef?.current ?? prevFocusRef.current;
    target?.focus();
  }, [open, returnFocusRef]);

  useEffect(() => {
    if (!open || !dismissible) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onOpenChange(false);
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, dismissible, onOpenChange]);

  useEffect(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = prev;
    };
  }, [open]);

  if (!open || typeof document === 'undefined') return null;

  const titleId = title ? 'ik-sheet-title' : undefined;
  const descId = description ? 'ik-sheet-desc' : undefined;

  const onOverlayMouseDown = (e: MouseEvent<HTMLDivElement>) => {
    if (dismissible && e.target === e.currentTarget) handleClose();
  };

  return createPortal(
    <div className="ik-sheet-overlay" onMouseDown={onOverlayMouseDown}>
      <div
        ref={sheetRef}
        className={cx('ik-sheet', `ik-sheet-snap-${snap}`, className)}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        aria-describedby={descId}
        tabIndex={-1}
      >
        {showHandle && (
          <div className="ik-sheet-handle" aria-hidden="true">
            <span className="ik-sheet-handle-bar" />
          </div>
        )}
        {(title || showClose) && (
          <div className="ik-sheet-header">
            <div>
              {title && (
                <div id={titleId} className="ik-sheet-title">
                  {title}
                </div>
              )}
              {description && (
                <div id={descId} className="ik-sheet-desc">
                  {description}
                </div>
              )}
            </div>
            {showClose && (
              <button
                type="button"
                className="ik-sheet-close"
                onClick={handleClose}
                aria-label={resolvedCloseLabel}
              >
                <svg
                  width="13"
                  height="13"
                  viewBox="0 0 16 16"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="1.6"
                  strokeLinecap="round"
                  aria-hidden="true"
                >
                  <line x1="4" y1="4" x2="12" y2="12" />
                  <line x1="12" y1="4" x2="4" y2="12" />
                </svg>
              </button>
            )}
          </div>
        )}
        {children != null && <div className="ik-sheet-body">{children}</div>}
        {footer && <div className="ik-sheet-footer">{footer}</div>}
      </div>
    </div>,
    document.body,
  );
}
