// packages/react/src/components/Avatar/Avatar.tsx
import { useState, type HTMLAttributes } from 'react'
import { cx } from '../../utils/cx.js'
import './Avatar.css'

export type AvatarSize = 'sm' | 'md' | 'lg'
export type AvatarShape = 'circle' | 'square'
export type AvatarStatus = 'online' | 'warn' | 'off' | 'error'
export type AvatarStatusDisplay = 'ring' | 'none'

export interface AvatarProps extends HTMLAttributes<HTMLSpanElement> {
  /** Display name — used for the accessible label and initials fallback. */
  name?: string
  src?: string
  size?: AvatarSize
  shape?: AvatarShape
  status?: AvatarStatus
  /** How to render presence status. Default: coloured ring around the avatar. */
  statusDisplay?: AvatarStatusDisplay
}

function initials(name?: string): string {
  if (!name) return '?'
  const parts = name.trim().split(/\s+/).slice(0, 2)
  return parts.map((p) => p[0] ?? '').join('') || '?'
}

/** Avatar — user representation with image or initials fallback + optional status ring. */
export function Avatar({
  name,
  src,
  size = 'md',
  shape = 'circle',
  status,
  statusDisplay = 'ring',
  className,
  ...rest
}: AvatarProps) {
  const [failed, setFailed] = useState(false)
  const showImg = src && !failed
  const showRing = status && statusDisplay === 'ring'

  return (
    <span
      className={cx(
        'ik-av-wrap',
        showRing && `ik-av-ring-${status}`,
        className,
      )}
      {...rest}
    >
      <span
        className={cx('ik-av', `ik-av-${size}`, `ik-av-${shape}`)}
        role="img"
        aria-label={name}
      >
        {showImg ? (
          <img className="ik-av-img" src={src} alt="" onError={() => setFailed(true)} />
        ) : (
          <span aria-hidden="true">{initials(name)}</span>
        )}
      </span>
    </span>
  )
}

// packages/vue/src/components/Avatar.vue
<script lang="ts">
export type AvatarSize = 'sm' | 'md' | 'lg';
export type AvatarShape = 'circle' | 'square';
export type AvatarStatus = 'online' | 'warn' | 'off' | 'error';
export type AvatarStatusDisplay = 'ring' | 'none';
</script>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { cx } from '../utils/cx.js';

const props = withDefaults(
  defineProps<{
    name?: string;
    src?: string;
    size?: AvatarSize;
    shape?: AvatarShape;
    status?: AvatarStatus;
    statusDisplay?: AvatarStatusDisplay;
  }>(),
  {
    size: 'md',
    shape: 'circle',
    statusDisplay: 'ring',
  },
);

const failed = ref(false);
const showImg = computed(() => props.src && !failed.value);
const showRing = computed(() => props.status && props.statusDisplay === 'ring');

const wrapCls = computed(() => cx('ik-av-wrap', showRing.value && `ik-av-ring-${props.status}`));
const avCls = computed(() => cx('ik-av', `ik-av-${props.size}`, `ik-av-${props.shape}`));

const initials = computed(() => {
  if (!props.name) return '?';
  const parts = props.name.trim().split(/\s+/).slice(0, 2);
  return parts.map((p) => p[0] ?? '').join('') || '?';
});

function onImgError() {
  failed.value = true;
}
</script>

<template>
  <span :class="wrapCls">
    <span :class="avCls" role="img" :aria-label="name">
      <img v-if="showImg" class="ik-av-img" :src="src" alt="" @error="onImgError" />
      <span v-else aria-hidden="true">{{ initials }}</span>
    </span>
  </span>
</template>
