// packages/react/src/components/ContextMenu/ContextMenuItem.tsx
import { useEffect, useId, useRef, type KeyboardEvent, type ReactNode } from 'react';
import { isActivationKey } from '@iskra-ui/core';
import { cx } from '../../utils/cx.js';
import { useContextMenu } from './context.js';

export interface ContextMenuItemProps {
  children: ReactNode;
  onSelect?: () => void;
  disabled?: boolean;
  destructive?: boolean;
  icon?: ReactNode;
  className?: string;
}

/**
 * Menu action item. Invokes `onSelect` and closes the menu on activation.
 */
export function ContextMenuItem({
  children,
  onSelect,
  disabled = false,
  destructive = false,
  icon,
  className,
}: ContextMenuItemProps) {
  const itemId = useId();
  const buttonRef = useRef<HTMLButtonElement>(null);
  const { items, registerItem, unregisterItem, activeIndex, setActiveIndex, close, triggerRef } =
    useContextMenu();

  const isActive = items[activeIndex]?.id === itemId;
  const tabIndex = isActive ? 0 : -1;

  useEffect(() => {
    registerItem({
      id: itemId,
      disabled,
      focus: () => buttonRef.current?.focus(),
    });
    return () => unregisterItem(itemId);
  }, [itemId, disabled, registerItem, unregisterItem]);

  const handleSelect = () => {
    if (disabled) return;
    onSelect?.();
    close();
    triggerRef.current?.focus();
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLButtonElement>) => {
    if (!isActivationKey(e.key)) return;
    e.preventDefault();
    handleSelect();
  };

  return (
    <button
      ref={buttonRef}
      type="button"
      role="menuitem"
      disabled={disabled}
      tabIndex={tabIndex}
      className={cx(
        'ik-context-menu-item',
        destructive && 'ik-context-menu-item--destructive',
        className,
      )}
      onClick={handleSelect}
      onKeyDown={handleKeyDown}
      onFocus={() => {
        const idx = items.findIndex((entry) => entry.id === itemId);
        if (idx >= 0) setActiveIndex(idx);
      }}
    >
      {icon ? (
        <span className="ik-context-menu-item-icon" aria-hidden="true">
          {icon}
        </span>
      ) : null}
      <span className="ik-context-menu-item-label">{children}</span>
    </button>
  );
}

// packages/vue/src/components/ContextMenuItem.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import { createId, isActivationKey } from '@iskra-ui/core';
import { cx } from '../utils/cx.js';
import { useContextMenuContext } from '../composables/contextMenu.js';

const props = withDefaults(
  defineProps<{
    disabled?: boolean;
    destructive?: boolean;
    class?: string;
  }>(),
  {
    disabled: false,
    destructive: false,
  },
);

const emit = defineEmits<{ select: [] }>();

const ctx = useContextMenuContext('ContextMenuItem');

const itemId = createId('ik-context-menu-item');
const buttonRef = ref<HTMLButtonElement | null>(null);

const isActive = computed(() => ctx.items.value[ctx.activeIndex.value]?.id === itemId);
const tabIndex = computed(() => (isActive.value ? 0 : -1));

const handleSelect = () => {
  if (props.disabled) return;
  emit('select');
  ctx.close();
  ctx.triggerRef.value?.focus();
};

const handleKeyDown = (e: KeyboardEvent) => {
  if (!isActivationKey(e.key)) return;
  e.preventDefault();
  handleSelect();
};

onMounted(() => {
  ctx.registerItem({
    id: itemId,
    disabled: props.disabled,
    focus: () => buttonRef.value?.focus(),
  });
});

watch(
  () => props.disabled,
  (disabled) => {
    ctx.registerItem({
      id: itemId,
      disabled,
      focus: () => buttonRef.value?.focus(),
    });
  },
);

onUnmounted(() => {
  ctx.unregisterItem(itemId);
});
</script>

<template>
  <button
    ref="buttonRef"
    type="button"
    role="menuitem"
    :disabled="disabled"
    :tabindex="tabIndex"
    :class="cx('ik-context-menu-item', destructive && 'ik-context-menu-item--destructive', props.class)"
    @click="handleSelect"
    @keydown="handleKeyDown"
    @focus="
      () => {
        const idx = ctx.items.value.findIndex((entry) => entry.id === itemId);
        if (idx >= 0) ctx.setActiveIndex(idx);
      }
    "
  >
    <span v-if="$slots.icon" class="ik-context-menu-item-icon" aria-hidden="true">
      <slot name="icon" />
    </span>
    <span class="ik-context-menu-item-label">
      <slot />
    </span>
  </button>
</template>
