// packages/react/src/components/Drawer/Drawer.tsx
import { useEffect, useId, useRef, type MouseEvent, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { useFocusTrap } from '../../utils/useFocusTrap.js';
import { cx } from '../../utils/cx.js';
import './Drawer.css';

export type DrawerSide = 'left' | 'right';

export interface DrawerProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  side?: DrawerSide;
  title?: ReactNode;
  /** Required when `title` is omitted — names the dialog for screen readers. */
  'aria-label'?: string;
  closeOnOverlay?: boolean;
  closeOnEsc?: boolean;
  children?: ReactNode;
  className?: string;
  returnFocusRef?: React.RefObject<HTMLElement | null>;
}

/**
 * Drawer — off-canvas panel for compact navigation. Wrap `Sidebar` or custom nav.
 * Implements `role="dialog"`, focus trap, Esc / overlay dismiss, focus restoration.
 */
export function Drawer({
  open,
  onOpenChange,
  side = 'left',
  title,
  'aria-label': ariaLabel,
  closeOnOverlay = true,
  closeOnEsc = true,
  children,
  className,
  returnFocusRef,
}: DrawerProps) {
  const panelRef = useRef<HTMLDivElement>(null);
  const prevFocusRef = useRef<HTMLElement | null>(null);
  const titleId = useId();
  useFocusTrap(panelRef, open);

  const handleClose = () => onOpenChange(false);

  useEffect(() => {
    if (open) {
      prevFocusRef.current = document.activeElement as HTMLElement | null;
      return;
    }
    const target = returnFocusRef?.current ?? prevFocusRef.current;
    target?.focus();
  }, [open, returnFocusRef]);

  useEffect(() => {
    if (!open || !closeOnEsc) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onOpenChange(false);
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, closeOnEsc, onOpenChange]);

  useEffect(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = prev;
    };
  }, [open]);

  if (!open || typeof document === 'undefined') return null;

  const label = ariaLabel ?? (typeof title === 'string' ? title : undefined);

  const onOverlayMouseDown = (e: MouseEvent<HTMLDivElement>) => {
    if (closeOnOverlay && e.target === e.currentTarget) handleClose();
  };

  return createPortal(
    <div className="ik-drawer-overlay" onMouseDown={onOverlayMouseDown}>
      <div
        ref={panelRef}
        className={cx('ik-drawer-panel', side === 'right' ? 'is-right' : 'is-left', className)}
        role="dialog"
        aria-modal="true"
        aria-labelledby={title ? titleId : undefined}
        aria-label={!title ? label : undefined}
        tabIndex={-1}
      >
        {title && (
          <span id={titleId} className="ik-sr-only">
            {title}
          </span>
        )}
        <div className="ik-drawer-body">{children}</div>
      </div>
    </div>,
    document.body,
  );
}

// packages/vue/src/components/Drawer.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue';
import { createFocusTrap } from '@iskra-ui/core';
import { cx } from '../utils/cx.js';

export type DrawerSide = 'left' | 'right';

const props = withDefaults(
  defineProps<{
    open: boolean;
    side?: DrawerSide;
    title?: string;
    ariaLabel?: string;
    closeOnOverlay?: boolean;
    closeOnEsc?: boolean;
  }>(),
  {
    side: 'left',
    closeOnOverlay: true,
    closeOnEsc: true,
  },
);

const emit = defineEmits<{ 'update:open': [open: boolean] }>();

const panelRef = ref<HTMLDivElement | null>(null);
const prevFocus = ref<HTMLElement | null>(null);
let trap: ReturnType<typeof createFocusTrap> | null = null;

const handleClose = () => emit('update:open', false);

watch(
  () => props.open,
  (open) => {
    if (open) {
      prevFocus.value = document.activeElement as HTMLElement | null;
      document.body.style.overflow = 'hidden';
      requestAnimationFrame(() => {
        if (panelRef.value) trap = createFocusTrap(panelRef.value);
        trap?.activate();
      });
      return;
    }
    trap?.deactivate();
    trap = null;
    document.body.style.overflow = '';
    prevFocus.value?.focus();
  },
);

function onKey(e: KeyboardEvent) {
  if (props.closeOnEsc && props.open && e.key === 'Escape') handleClose();
}

function onOverlayMouseDown(e: MouseEvent) {
  if (props.closeOnOverlay && e.target === e.currentTarget) handleClose();
}

onMounted(() => document.addEventListener('keydown', onKey));
onUnmounted(() => {
  document.removeEventListener('keydown', onKey);
  trap?.deactivate();
  document.body.style.overflow = '';
});
</script>

<template>
  <Teleport to="body">
    <div v-if="open" class="ik-drawer-overlay" @mousedown="onOverlayMouseDown">
      <div
        ref="panelRef"
        :class="cx('ik-drawer-panel', side === 'right' ? 'is-right' : 'is-left')"
        role="dialog"
        aria-modal="true"
        :aria-label="title ? undefined : ariaLabel"
        :aria-labelledby="title ? 'ik-drawer-title' : undefined"
        tabindex="-1"
      >
        <span v-if="title" id="ik-drawer-title" class="ik-sr-only">{{ title }}</span>
        <div class="ik-drawer-body">
          <slot />
        </div>
      </div>
    </div>
  </Teleport>
</template>
