// packages/react/src/components/MobileNav/MobileNav.tsx
import { useState, type ReactNode } from 'react';
import { resolvePrimaryNavItems, type SidebarNavGroup, type SidebarNavItem } from '@iskra-ui/core';
import { useIskraT } from '../../i18n/useIskraT.js';
import { cx } from '../../utils/cx.js';
import { Icon } from '../Icon/Icon.js';
import { Sheet } from '../Sheet/Sheet.js';
import type { IconName } from '@iskra-ui/icons';
import './MobileNav.css';

export interface MobileNavProps {
  groups: SidebarNavGroup[];
  footerItems?: SidebarNavItem[];
  primaryItems: string[];
  activeItem?: string;
  onNavigate?: (id: string) => void;
  onItemClick?: (item: SidebarNavItem) => void;
  menuLabel?: string;
  sheetTitle?: ReactNode;
  badges?: Record<string, number>;
  ariaLabel?: string;
  className?: string;
}

function NavListItem({
  item,
  active,
  badge,
  onSelect,
}: {
  item: SidebarNavItem;
  active: boolean;
  badge?: number;
  onSelect: (item: SidebarNavItem) => void;
}) {
  return (
    <button
      type="button"
      className={cx('imn-sheet-item', active && 'imn-sheet-item--on')}
      disabled={item.disabled}
      aria-current={active ? 'page' : undefined}
      onClick={() => onSelect(item)}
    >
      <span className="imn-sheet-item-ico">
        {item.icon ? <Icon name={item.icon as IconName} size={16} /> : null}
      </span>
      <span className="imn-sheet-item-lbl">{item.label}</span>
      {badge != null && badge > 0 && (
        <span className="imn-sheet-item-bdg" aria-label={`${item.label}: ${badge}`}>
          {badge}
        </span>
      )}
    </button>
  );
}

/**
 * MobileNav — fixed bottom navigation bar for viewports below `bp-md`.
 * Shows up to four primary items plus a menu button that opens a Sheet with full nav.
 */
export function MobileNav({
  groups,
  footerItems = [],
  primaryItems,
  activeItem,
  onNavigate,
  onItemClick,
  menuLabel,
  sheetTitle,
  badges = {},
  ariaLabel,
  className,
}: MobileNavProps) {
  const t = useIskraT();
  const [menuOpen, setMenuOpen] = useState(false);
  const resolvedAriaLabel = ariaLabel ?? t('a11y.mobileNavigation');
  const resolvedMenuLabel = menuLabel ?? t('a11y.openMenu');
  const resolvedSheetTitle = sheetTitle ?? t('a11y.moreNavigation');
  const primary = resolvePrimaryNavItems(groups, primaryItems, 4);

  const handleSelect = (item: SidebarNavItem) => {
    onItemClick?.(item);
    onNavigate?.(item.id);
    setMenuOpen(false);
  };

  const isMenuActive = primary.every((item) => item.id !== activeItem) && activeItem != null;

  return (
    <>
      <nav
        className={cx('iskra-mobile-nav', className)}
        role="navigation"
        aria-label={resolvedAriaLabel}
      >
        {primary.map((item) => {
          const badge = badges[item.id] ?? item.badge;
          const active = activeItem === item.id;
          return (
            <button
              key={item.id}
              type="button"
              className={cx('imn-tab', active && 'imn-tab--on')}
              disabled={item.disabled}
              aria-current={active ? 'page' : undefined}
              onClick={() => handleSelect(item)}
            >
              <span className="imn-tab-ico">
                {item.icon ? <Icon name={item.icon as IconName} size={18} /> : null}
              </span>
              <span className="imn-tab-lbl">{item.label}</span>
              {badge != null && badge > 0 && (
                <span className="imn-tab-bdg" aria-hidden="true">
                  {badge > 9 ? '9+' : badge}
                </span>
              )}
            </button>
          );
        })}
        <button
          type="button"
          className={cx('imn-tab', isMenuActive && 'imn-tab--on')}
          aria-label={resolvedMenuLabel}
          aria-expanded={menuOpen}
          onClick={() => setMenuOpen(true)}
        >
          <span className="imn-tab-ico">
            <Icon name="grid" size={18} />
          </span>
          <span className="imn-tab-lbl">{resolvedMenuLabel}</span>
        </button>
      </nav>

      <Sheet open={menuOpen} onOpenChange={setMenuOpen} title={resolvedSheetTitle} snap="half">
        <div className="imn-sheet-body">
          {groups.map((group, index) => (
            <div key={group.id} className="imn-sheet-grp">
              {index > 0 ? <div className="imn-sheet-divider" role="separator" /> : null}
              {group.label ? (
                <div className="imn-sheet-sec" aria-hidden="true">
                  {group.label}
                </div>
              ) : null}
              {group.items.map((item) => (
                <NavListItem
                  key={item.id}
                  item={item}
                  active={activeItem === item.id}
                  badge={badges[item.id] ?? item.badge}
                  onSelect={handleSelect}
                />
              ))}
            </div>
          ))}
          {footerItems.length > 0 ? (
            <div className="imn-sheet-grp">
              <div className="imn-sheet-divider" role="separator" />
              {footerItems.map((item) => (
                <NavListItem
                  key={item.id}
                  item={item}
                  active={activeItem === item.id}
                  badge={badges[item.id] ?? item.badge}
                  onSelect={handleSelect}
                />
              ))}
            </div>
          ) : null}
        </div>
      </Sheet>
    </>
  );
}

// packages/vue/src/components/MobileNav.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import {
  resolvePrimaryNavItems,
  type SidebarNavGroup,
  type SidebarNavItem,
} from '@iskra-ui/core';
import { useIskraT } from '../i18n/useIskraT.js';
import Icon from './Icon.vue';
import Sheet from './Sheet.vue';
import { cx } from '../utils/cx.js';
import type { IconName } from '@iskra-ui/icons';

const props = withDefaults(
  defineProps<{
    groups: SidebarNavGroup[];
    footerItems?: SidebarNavItem[];
    primaryItems: string[];
    activeItem?: string;
    menuLabel?: string;
    sheetTitle?: string;
    badges?: Record<string, number>;
    ariaLabel?: string;
    class?: string;
  }>(),
  {
    footerItems: () => [],
    badges: () => ({}),
  },
);

const emit = defineEmits<{
  navigate: [id: string];
  itemClick: [item: SidebarNavItem];
}>();

const t = useIskraT();
const menuOpen = ref(false);

const resolvedAriaLabel = computed(() => props.ariaLabel ?? t('a11y.mobileNavigation'));
const resolvedMenuLabel = computed(() => props.menuLabel ?? t('a11y.openMenu'));
const resolvedSheetTitle = computed(() => props.sheetTitle ?? t('a11y.moreNavigation'));
const primary = computed(() => resolvePrimaryNavItems(props.groups, props.primaryItems, 4));

const isMenuActive = computed(
  () =>
    props.activeItem != null &&
    !primary.value.some((item) => item.id === props.activeItem),
);

function badgeFor(item: SidebarNavItem) {
  return props.badges[item.id] ?? item.badge;
}

function handleSelect(item: SidebarNavItem) {
  emit('itemClick', item);
  emit('navigate', item.id);
  menuOpen.value = false;
}
</script>

<template>
  <nav :class="cx('iskra-mobile-nav', $props.class)" role="navigation" :aria-label="resolvedAriaLabel">
    <button
      v-for="item in primary"
      :key="item.id"
      type="button"
      :class="cx('imn-tab', activeItem === item.id && 'imn-tab--on')"
      :disabled="item.disabled"
      :aria-current="activeItem === item.id ? 'page' : undefined"
      @click="handleSelect(item)"
    >
      <span class="imn-tab-ico">
        <Icon v-if="item.icon" :name="item.icon as IconName" :size="18" />
      </span>
      <span class="imn-tab-lbl">{{ item.label }}</span>
      <span
        v-if="badgeFor(item) != null && badgeFor(item)! > 0"
        class="imn-tab-bdg"
        aria-hidden="true"
      >
        {{ badgeFor(item)! > 9 ? '9+' : badgeFor(item) }}
      </span>
    </button>

    <button
      type="button"
      :class="cx('imn-tab', isMenuActive && 'imn-tab--on')"
      :aria-label="resolvedMenuLabel"
      :aria-expanded="menuOpen"
      @click="menuOpen = true"
    >
      <span class="imn-tab-ico">
        <Icon name="grid" :size="18" />
      </span>
      <span class="imn-tab-lbl">{{ resolvedMenuLabel }}</span>
    </button>
  </nav>

  <Sheet v-model:open="menuOpen" :title="resolvedSheetTitle" snap="half">
    <div class="imn-sheet-body">
      <div v-for="(group, index) in groups" :key="group.id" class="imn-sheet-grp">
        <div v-if="index > 0" class="imn-sheet-divider" role="separator" />
        <div v-if="group.label" class="imn-sheet-sec" aria-hidden="true">{{ group.label }}</div>
        <button
          v-for="item in group.items"
          :key="item.id"
          type="button"
          :class="cx('imn-sheet-item', activeItem === item.id && 'imn-sheet-item--on')"
          :disabled="item.disabled"
          :aria-current="activeItem === item.id ? 'page' : undefined"
          @click="handleSelect(item)"
        >
          <span class="imn-sheet-item-ico">
            <Icon v-if="item.icon" :name="item.icon as IconName" :size="16" />
          </span>
          <span class="imn-sheet-item-lbl">{{ item.label }}</span>
          <span
            v-if="badgeFor(item) != null && badgeFor(item)! > 0"
            class="imn-sheet-item-bdg"
            :aria-label="`${item.label}: ${badgeFor(item)}`"
          >
            {{ badgeFor(item) }}
          </span>
        </button>
      </div>

      <div v-if="footerItems.length" class="imn-sheet-grp">
        <div class="imn-sheet-divider" role="separator" />
        <button
          v-for="item in footerItems"
          :key="item.id"
          type="button"
          :class="cx('imn-sheet-item', activeItem === item.id && 'imn-sheet-item--on')"
          :aria-current="activeItem === item.id ? 'page' : undefined"
          @click="handleSelect(item)"
        >
          <span class="imn-sheet-item-ico">
            <Icon v-if="item.icon" :name="item.icon as IconName" :size="16" />
          </span>
          <span class="imn-sheet-item-lbl">{{ item.label }}</span>
        </button>
      </div>
    </div>
  </Sheet>
</template>
