// packages/react/src/components/Table/Table.tsx
import { type ReactNode } from 'react'
import { Icon } from '../Icon/Icon.js'
import { Skeleton } from '../Skeleton/Skeleton.js'
import { cx } from '../../utils/cx.js'
import './Table.css'

export type TableDensity = 'regular' | 'compact'
export type TableAlign = 'left' | 'right' | 'center'
export type SortDirection = 'asc' | 'desc'

export interface TableSort {
  key: string
  direction: SortDirection
}

export interface TableColumn<T> {
  key: string
  header: ReactNode
  render?: (row: T, index: number) => ReactNode
  align?: TableAlign
  width?: number | string
  sortable?: boolean
  sortKey?: string
  filter?: ReactNode
}

export interface TableProps<T> {
  columns: TableColumn<T>[]
  data: T[]
  getRowId?: (row: T, index: number) => string | number
  density?: TableDensity
  stickyHeader?: boolean
  loading?: boolean
  loadingRows?: number
  empty?: ReactNode
  onRowClick?: (row: T, index: number) => void
  selectedRowId?: string | number
  caption?: string
  sort?: TableSort | null
  onSortChange?: (sort: TableSort | null) => void
  className?: string
}

const alignClass = (a?: TableAlign) =>
  a === 'right' ? 'ik-table-align-right' : a === 'center' ? 'ik-table-align-center' : undefined

function HeaderCell<T>({
  col,
  sort,
  onSortChange,
}: {
  col: TableColumn<T>
  sort?: TableSort | null
  onSortChange?: (sort: TableSort | null) => void
}) {
  const sk = col.sortKey ?? col.key
  const isActive = sort?.key === sk

  const handleSort = () => {
    if (!col.sortable || !onSortChange) return
    if (!isActive) onSortChange({ key: sk, direction: 'asc' })
    else if (sort!.direction === 'asc') onSortChange({ key: sk, direction: 'desc' })
    else onSortChange(null)
  }

  const content = (
    <span className="ik-table-th-inner">
      <span className="ik-table-th-label">{col.header}</span>
      {col.sortable && (
        <span className="ik-table-sort-icons" aria-hidden="true">
          <Icon
            name="chevron-up"
            size={10}
            style={{ opacity: isActive && sort?.direction === 'asc' ? 1 : 0.35 }}
          />
          <Icon
            name="chevron-down"
            size={10}
            style={{ opacity: isActive && sort?.direction === 'desc' ? 1 : 0.35 }}
          />
        </span>
      )}
      {col.filter && <span className="ik-table-th-filter">{col.filter}</span>}
    </span>
  )

  if (col.sortable) {
    return (
      <button type="button" className="ik-table-sort-btn" onClick={handleSort}>
        {content}
      </button>
    )
  }

  return content
}

/** Table — foundational data table with optional column sort and filter slots. */
export function Table<T>({
  columns,
  data,
  getRowId,
  density = 'regular',
  stickyHeader = false,
  loading = false,
  loadingRows = 5,
  empty,
  onRowClick,
  selectedRowId,
  caption,
  sort,
  onSortChange,
  className,
}: TableProps<T>) {
  const colCount = columns.length
  const rowId = (row: T, i: number) => getRowId?.(row, i) ?? i

  return (
    <div className="ik-table-wrap">
      <table
        className={cx(
          'ik-table',
          `ik-table-${density}`,
          stickyHeader && 'ik-table-sticky',
          className,
        )}
      >
        {caption && <caption>{caption}</caption>}
        <thead>
          <tr>
            {columns.map((c) => (
              <th
                key={c.key}
                scope="col"
                className={alignClass(c.align)}
                style={{ width: c.width }}
                aria-sort={
                  c.sortable
                    ? sort?.key === (c.sortKey ?? c.key)
                      ? sort.direction === 'asc'
                        ? 'ascending'
                        : 'descending'
                      : 'none'
                    : undefined
                }
              >
                <HeaderCell col={c} sort={sort} onSortChange={onSortChange} />
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {loading ? (
            Array.from({ length: loadingRows }).map((_, r) => (
              <tr key={`sk-${r}`}>
                {columns.map((c) => (
                  <td key={c.key} className={alignClass(c.align)}>
                    <Skeleton variant="text" />
                  </td>
                ))}
              </tr>
            ))
          ) : data.length === 0 ? (
            <tr>
              <td className="ik-table-state" colSpan={colCount}>
                {empty}
              </td>
            </tr>
          ) : (
            data.map((row, i) => {
              const id = rowId(row, i)
              return (
                <tr
                  key={id}
                  className={cx(
                    onRowClick && 'ik-table-row-clickable',
                    selectedRowId != null && selectedRowId === id && 'ik-table-row-selected',
                  )}
                  aria-selected={selectedRowId != null ? selectedRowId === id : undefined}
                  onClick={onRowClick ? () => onRowClick(row, i) : undefined}
                >
                  {columns.map((c) => (
                    <td key={c.key} className={alignClass(c.align)}>
                      {c.render
                        ? c.render(row, i)
                        : ((row as Record<string, ReactNode>)[c.key] ?? null)}
                    </td>
                  ))}
                </tr>
              )
            })
          )}
        </tbody>
      </table>
    </div>
  )
}

// packages/vue/src/components/Table.vue
<script lang="ts">
export type TableDensity = 'regular' | 'compact';
export type TableAlign = 'left' | 'right' | 'center';
export type SortDirection = 'asc' | 'desc';

export interface TableSort {
  key: string;
  direction: SortDirection;
}

export interface TableColumn {
  key: string;
  header: string;
  align?: TableAlign;
  width?: number | string;
  sortable?: boolean;
  sortKey?: string;
}
</script>

<script setup lang="ts" generic="T extends Record<string, unknown>">
import { computed } from 'vue';
import { cx } from '../utils/cx.js';
import Icon from './Icon.vue';

const props = withDefaults(
  defineProps<{
    columns: TableColumn[];
    data: T[];
    density?: TableDensity;
    stickyHeader?: boolean;
    loading?: boolean;
    loadingRows?: number;
    sort?: TableSort | null;
    caption?: string;
  }>(),
  {
    density: 'regular',
    stickyHeader: false,
    loading: false,
    loadingRows: 5,
    sort: null,
  },
);

const emit = defineEmits<{
  sortChange: [sort: TableSort | null];
  rowClick: [row: T, index: number];
}>();

const tableCls = computed(() =>
  cx('ik-table', `ik-table-${props.density}`, props.stickyHeader && 'ik-table-sticky'),
);

const alignClass = (a?: TableAlign) =>
  a === 'right' ? 'ik-table-align-right' : a === 'center' ? 'ik-table-align-center' : undefined;

function sortKey(col: TableColumn) {
  return col.sortKey ?? col.key;
}

function ariaSort(col: TableColumn) {
  if (!col.sortable) return undefined;
  const sk = sortKey(col);
  if (props.sort?.key !== sk) return 'none';
  return props.sort.direction === 'asc' ? 'ascending' : 'descending';
}

function handleSort(col: TableColumn) {
  if (!col.sortable) return;
  const sk = sortKey(col);
  if (props.sort?.key !== sk) emit('sortChange', { key: sk, direction: 'asc' });
  else if (props.sort.direction === 'asc') emit('sortChange', { key: sk, direction: 'desc' });
  else emit('sortChange', null);
}
</script>

<template>
  <div class="ik-table-wrap">
    <table :class="tableCls">
      <caption v-if="caption">
        {{
          caption
        }}
      </caption>
      <thead>
        <tr>
          <th
            v-for="col in columns"
            :key="col.key"
            scope="col"
            :class="alignClass(col.align)"
            :style="
              col.width
                ? { width: typeof col.width === 'number' ? `${col.width}px` : col.width }
                : undefined
            "
            :aria-sort="ariaSort(col)"
          >
            <button
              v-if="col.sortable"
              type="button"
              class="ik-table-sort-btn"
              @click="handleSort(col)"
            >
              <span class="ik-table-th-inner">
                <span class="ik-table-th-label">{{ col.header }}</span>
                <span class="ik-table-sort-icons" aria-hidden="true">
                  <Icon
                    name="chevron-up"
                    :size="10"
                    :style="{
                      opacity: sort?.key === sortKey(col) && sort?.direction === 'asc' ? 1 : 0.35,
                    }"
                  />
                  <Icon
                    name="chevron-down"
                    :size="10"
                    :style="{
                      opacity: sort?.key === sortKey(col) && sort?.direction === 'desc' ? 1 : 0.35,
                    }"
                  />
                </span>
              </span>
            </button>
            <span v-else class="ik-table-th-inner">
              <span class="ik-table-th-label">{{ col.header }}</span>
              <span v-if="$slots[`filter-${col.key}`]" class="ik-table-th-filter">
                <slot :name="`filter-${col.key}`" />
              </span>
            </span>
          </th>
        </tr>
      </thead>
      <tbody>
        <template v-if="loading">
          <tr v-for="r in loadingRows" :key="`sk-${r}`">
            <td v-for="col in columns" :key="col.key" :class="alignClass(col.align)">
              <div class="ik-skeleton ik-skeleton-text" aria-hidden="true" />
            </td>
          </tr>
        </template>
        <tr v-else-if="!data.length">
          <td class="ik-table-state" :colspan="columns.length">
            <slot name="empty" />
          </td>
        </tr>
        <tr
          v-for="(row, i) in data"
          v-else
          :key="String(row.id ?? i)"
          @click="emit('rowClick', row, i)"
        >
          <td v-for="col in columns" :key="col.key" :class="alignClass(col.align)">
            <slot :name="`cell-${col.key}`" :row="row" :index="i">
              {{ row[col.key] }}
            </slot>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
