// packages/vue/src/components/Sidebar.vue
<script setup lang="ts">
import { computed, onMounted, ref, useAttrs, watch } from 'vue';
import Icon from './Icon.vue';
import { cx } from '../utils/cx.js';
import type { IconName } from '@iskra-ui/icons';
import {
  resolveSidebarGroups,
  type SidebarNavGroup,
  type SidebarNavItem,
  type SidebarVariant,
} from '@iskra-ui/core';

export type SidebarTheme = '' | 'theme-cold' | 'theme-warm';

const props = withDefaults(
  defineProps<{
    groups?: SidebarNavGroup[];
    footerItems?: SidebarNavItem[];
    collapsed?: boolean;
    collapsible?: boolean;
    activeItem?: string;
    variant?: SidebarVariant;
    theme?: SidebarTheme;
    badges?: Record<string, number>;
    ariaLabel?: string;
  }>(),
  {
    footerItems: () => [],
    collapsed: false,
    collapsible: true,
    variant: 'operator',
    theme: '',
    badges: () => ({}),
    ariaLabel: 'Навигация',
  },
);

const emit = defineEmits<{
  navigate: [id: string];
  itemClick: [item: SidebarNavItem];
  toggle: [];
}>();

const sbRef = ref<HTMLElement | null>(null);
const tip = ref<{ lbl: string; top: number } | null>(null);
const tipRdy = ref(false);

const attrs = useAttrs();

const groups = computed(() => props.groups ?? resolveSidebarGroups(props.variant));
const showCollapser = computed(() => props.collapsible && typeof attrs.onToggle !== 'undefined');

const sbCls = computed(() =>
  cx(
    'iskra-sb',
    props.collapsed && 'isb-c',
    props.collapsed && tipRdy.value && 'isb-tip-rdy',
    props.theme,
  ),
);

function iconName(item: SidebarNavItem): IconName | undefined {
  return item.icon as IconName | undefined;
}

function badgeFor(item: SidebarNavItem) {
  return props.badges[item.id] ?? item.badge;
}

function onItemClick(item: SidebarNavItem) {
  emit('itemClick', item);
  emit('navigate', item.id);
}

function showTip(e: MouseEvent, lbl: string) {
  if (!tipRdy.value || !sbRef.value) return;
  const ir = (e.currentTarget as HTMLElement).getBoundingClientRect();
  const sr = sbRef.value.getBoundingClientRect();
  tip.value = { lbl, top: ir.top - sr.top + ir.height / 2 };
}

function hideTip() {
  tip.value = null;
}

watch(
  () => props.collapsed,
  (c) => {
    tipRdy.value = false;
    tip.value = null;
    if (c)
      setTimeout(() => {
        tipRdy.value = true;
      }, 210);
  },
);

onMounted(() => {
  if (props.collapsed)
    setTimeout(() => {
      tipRdy.value = true;
    }, 210);
});
</script>

<template>
  <aside ref="sbRef" :class="sbCls" role="navigation" :aria-label="ariaLabel">
    <div v-if="$slots.brand || showCollapser" class="isb-logo">
      <div v-if="$slots.brand" class="isb-brand">
        <slot name="brand" />
      </div>
      <button
        v-if="showCollapser"
        class="isb-collapser"
        type="button"
        :aria-expanded="!collapsed"
        :aria-label="collapsed ? 'Развернуть боковую панель' : 'Свернуть боковую панель'"
        @click="emit('toggle')"
      >
        <svg
          viewBox="0 0 10 10"
          fill="none"
          stroke="currentColor"
          stroke-width="1.5"
          aria-hidden="true"
        >
          <polyline points="7,2 4,5 7,8" />
        </svg>
      </button>
    </div>

    <div v-if="$slots.header" class="isb-head">
      <slot name="header" />
    </div>

    <div class="isb-scroll">
      <slot>
        <div v-for="grp in groups" :key="grp.id" class="isb-grp">
          <div v-if="grp.label" class="isb-sec" aria-hidden="true">{{ grp.label }}</div>
          <button
            v-for="item in grp.items"
            :key="item.id"
            type="button"
            :class="cx('isb-item', activeItem === item.id && 'isb-on')"
            :title="item.label"
            :disabled="item.disabled"
            :aria-current="activeItem === item.id ? 'page' : undefined"
            @click="onItemClick(item)"
            @mouseenter="collapsed ? showTip($event, item.label) : undefined"
            @mouseleave="collapsed ? hideTip() : undefined"
          >
            <span class="isb-ico">
              <Icon v-if="iconName(item)" :name="iconName(item)!" :size="16" />
            </span>
            <span class="isb-lbl">{{ item.label }}</span>
            <span
              v-if="badgeFor(item) != null && badgeFor(item)! > 0"
              class="isb-bdg"
              :aria-label="`${item.label}: ${badgeFor(item)}`"
            >
              {{ badgeFor(item) }}
            </span>
          </button>
        </div>
      </slot>
    </div>

    <div v-if="$slots.footer" class="isb-foot">
      <slot name="footer" />
    </div>
    <div v-else-if="footerItems.length" class="isb-foot">
      <button
        v-for="item in footerItems"
        :key="item.id"
        type="button"
        :class="cx('isb-item', activeItem === item.id && 'isb-on')"
        :title="item.label"
        :aria-current="activeItem === item.id ? 'page' : undefined"
        @click="onItemClick(item)"
        @mouseenter="collapsed ? showTip($event, item.label) : undefined"
        @mouseleave="collapsed ? hideTip() : undefined"
      >
        <span class="isb-ico">
          <Icon v-if="iconName(item)" :name="iconName(item)!" :size="16" />
        </span>
        <span class="isb-lbl">{{ item.label }}</span>
      </button>
    </div>

    <div v-if="tip" class="isb-floatip" :style="{ top: `${tip.top}px` }">
      {{ tip.lbl }}
    </div>
  </aside>
</template>

// packages/react/src/components/Sidebar/Sidebar.tsx
import { useCallback, useEffect, useRef, useState, type MouseEvent, type ReactNode } from 'react';
import { Icon } from '../Icon/Icon.js';
import { cx } from '../../utils/cx.js';
import type { IconName } from '@iskra-ui/icons';
import {
  resolveSidebarGroups,
  type SidebarNavGroup,
  type SidebarNavItem,
  type SidebarVariant,
} from '@iskra-ui/core';
import './Sidebar.css';

export type SidebarTheme = '' | 'theme-cold' | 'theme-warm';

export type { SidebarNavGroup, SidebarNavItem, SidebarVariant };
export {
  DCI_OPERATOR_NAV,
  DCI_ADMIN_NAV,
  DCI_FOOTER_NAV,
  NOTIFIER_NAV,
  resolveSidebarGroups,
} from './presets.js';

export interface SidebarItemRenderContext {
  active: boolean;
  collapsed: boolean;
  badge?: number;
}

export interface SidebarProps {
  /** Navigation tree. Omit when using `children` for a fully custom body. */
  groups?: SidebarNavGroup[];
  /** Declarative footer items (rendered as nav buttons). */
  footerItems?: SidebarNavItem[];
  /** Brand block in the top bar (logo, product name). No default — pass explicitly. */
  brand?: ReactNode;
  /** Optional content below the brand bar, above scrollable nav. */
  header?: ReactNode;
  /** Custom footer slot — overrides `footerItems` when set. */
  footer?: ReactNode;
  /** Replaces the default groups renderer in the scroll area. */
  children?: ReactNode;
  collapsed?: boolean;
  /** Show collapse control when `onToggle` is provided. Default: true. */
  collapsible?: boolean;
  onToggle?: () => void;
  activeItem?: string;
  onNavigate?: (id: string) => void;
  onItemClick?: (item: SidebarNavItem) => void;
  /** Convenience preset when `groups` is omitted. Prefer explicit `groups` in products. */
  variant?: SidebarVariant;
  theme?: SidebarTheme;
  badges?: Record<string, number>;
  ariaLabel?: string;
  renderItem?: (item: SidebarNavItem, ctx: SidebarItemRenderContext) => ReactNode;
  className?: string;
}

interface ItemProps {
  item: SidebarNavItem;
  active: boolean;
  collapsed: boolean;
  badge?: number;
  onHover?: (e: MouseEvent<HTMLButtonElement>, lbl: string) => void;
  onLeave?: () => void;
  onClick?: () => void;
  renderItem?: SidebarProps['renderItem'];
}

function DefaultItemButton({
  item,
  active,
  badge,
  onHover,
  onLeave,
  onClick,
}: Omit<ItemProps, 'collapsed' | 'renderItem'>) {
  return (
    <button
      className={cx('isb-item', active && 'isb-on')}
      title={item.label}
      onMouseEnter={onHover ? (e) => onHover(e, item.label) : undefined}
      onMouseLeave={onLeave}
      onClick={onClick}
      type="button"
      disabled={item.disabled}
      aria-current={active ? 'page' : undefined}
    >
      <span className="isb-ico">
        {item.icon ? <Icon name={item.icon as IconName} size={16} /> : null}
      </span>
      <span className="isb-lbl">{item.label}</span>
      {badge != null && badge > 0 && (
        <span className="isb-bdg" aria-label={`${item.label}: ${badge}`}>
          {badge}
        </span>
      )}
    </button>
  );
}

function Item(props: ItemProps) {
  const { renderItem, item, active, collapsed, badge, onClick, onHover, onLeave } = props;
  if (renderItem) {
    return (
      <div className="isb-item-wrap" onClick={onClick}>
        {renderItem(item, { active, collapsed, badge })}
      </div>
    );
  }
  return (
    <DefaultItemButton
      item={item}
      active={active}
      badge={badge}
      onClick={onClick}
      onHover={onHover}
      onLeave={onLeave}
    />
  );
}

function NavGroups({
  groups,
  activeItem,
  collapsed,
  badges,
  onItemActivate,
  hover,
  renderItem,
}: {
  groups: SidebarNavGroup[];
  activeItem?: string;
  collapsed: boolean;
  badges: Record<string, number>;
  onItemActivate: (item: SidebarNavItem) => void;
  hover: { onHover?: ItemProps['onHover']; onLeave?: ItemProps['onLeave'] };
  renderItem?: SidebarProps['renderItem'];
}) {
  return (
    <>
      {groups.map(({ id, label, items }) => (
        <div key={id} className="isb-grp">
          {label && (
            <div className="isb-sec" aria-hidden="true">
              {label}
            </div>
          )}
          {items.map((item) => (
            <Item
              key={item.id}
              item={item}
              active={activeItem === item.id}
              collapsed={collapsed}
              badge={badges[item.id] ?? item.badge}
              onClick={() => onItemActivate(item)}
              renderItem={renderItem}
              {...hover}
            />
          ))}
        </div>
      ))}
    </>
  );
}

/**
 * Sidebar — universal app navigation shell. Supply `groups` + `brand` per product,
 * or pass `children` for a fully custom body. Presets (`NOTIFIER_NAV`, …) live in
 * `@iskra-ui/core` for convenience only.
 */
export function Sidebar({
  groups: groupsProp,
  footerItems = [],
  brand,
  header,
  footer,
  children,
  collapsed = false,
  collapsible = true,
  onToggle,
  activeItem,
  onNavigate,
  onItemClick,
  variant = 'operator',
  theme = '',
  badges = {},
  ariaLabel = 'Навигация',
  renderItem,
  className = '',
}: SidebarProps) {
  const [tip, setTip] = useState<{ lbl: string; top: number } | null>(null);
  const [tipRdy, setTipRdy] = useState(false);
  const [prevCollapsed, setPrevCollapsed] = useState(collapsed);
  const sbRef = useRef<HTMLElement>(null);

  const groups = groupsProp ?? (children ? [] : resolveSidebarGroups(variant));
  const showCollapser = collapsible && typeof onToggle === 'function';

  if (collapsed !== prevCollapsed) {
    setPrevCollapsed(collapsed);
    setTipRdy(false);
    setTip(null);
  }

  useEffect(() => {
    if (!collapsed) return;
    const t = setTimeout(() => setTipRdy(true), 210);
    return () => clearTimeout(t);
  }, [collapsed]);

  const showTip = useCallback(
    (e: MouseEvent<HTMLButtonElement>, lbl: string) => {
      if (!tipRdy || !sbRef.current) return;
      const ir = e.currentTarget.getBoundingClientRect();
      const sr = sbRef.current.getBoundingClientRect();
      setTip({ lbl, top: ir.top - sr.top + ir.height / 2 });
    },
    [tipRdy],
  );

  const hideTip = useCallback(() => setTip(null), []);

  const hover = collapsed ? { onHover: showTip, onLeave: hideTip } : {};

  const handleItem = (item: SidebarNavItem) => {
    onItemClick?.(item);
    onNavigate?.(item.id);
  };

  return (
    <aside
      className={cx(
        'iskra-sb',
        collapsed && 'isb-c',
        collapsed && tipRdy && 'isb-tip-rdy',
        theme,
        className,
      )}
      ref={sbRef}
      role="navigation"
      aria-label={ariaLabel}
    >
      {(brand != null || showCollapser) && (
        <div className="isb-logo">
          {brand != null && <div className="isb-brand">{brand}</div>}
          {showCollapser && (
            <button
              className="isb-collapser"
              type="button"
              onClick={onToggle}
              aria-expanded={!collapsed}
              aria-label={collapsed ? 'Развернуть боковую панель' : 'Свернуть боковую панель'}
            >
              <svg
                viewBox="0 0 10 10"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden="true"
              >
                <polyline points="7,2 4,5 7,8" />
              </svg>
            </button>
          )}
        </div>
      )}

      {header != null && <div className="isb-head">{header}</div>}

      <div className="isb-scroll">
        {children ?? (
          <NavGroups
            groups={groups}
            activeItem={activeItem}
            collapsed={collapsed}
            badges={badges}
            onItemActivate={handleItem}
            hover={hover}
            renderItem={renderItem}
          />
        )}
      </div>

      {footer != null ? (
        <div className="isb-foot">{footer}</div>
      ) : footerItems.length > 0 ? (
        <div className="isb-foot">
          {footerItems.map((item) => (
            <Item
              key={item.id}
              item={item}
              active={activeItem === item.id}
              collapsed={collapsed}
              badge={badges[item.id] ?? item.badge}
              onClick={() => handleItem(item)}
              renderItem={renderItem}
              {...hover}
            />
          ))}
        </div>
      ) : null}

      {tip && (
        <div className="isb-floatip" style={{ top: tip.top }}>
          {tip.lbl}
        </div>
      )}
    </aside>
  );
}
